### PR TITLE
Issue 10 - Restore Java 1.5 compatibility

### PR DESCRIPTION
**Pull request by InfoSec812**
Previously, I when I had updated mockrunner-jdbc I had modified the POM files in order to resolve a classpath error and never modified them back.. This PR resolves those changes BACK to where the entire library is Java 1.5 compatible.

### CODE REVIEW

**Comment by InfoSec812** [comment]
FYI, this SHOULD resolve issue #10 and all tests are passing

**Comment by cemartins** [comment]
Hi Daven!

I don’t see a pull request pending. Did you merge it already? let me know and I’ll deploy the next version to maven central.

Cheers
Carlos

**Comment by InfoSec812** [comment]
No, apparently it didn't take. There is a branch for the changes in the
main project.

Deven Phillips
from my mobile

**Comment by cemartins** [comment]
Maybe Github has been out partying and got confused - I also don’t know why our conversation is logged at steinarb/mockrunner when our project is at mockrunner/mockrunner

We can merge your branch with master, though

Carlos

**Comment by cemartins** [comment]
It’s past 1am here, Daven. I’m turning in. I’ll look it up tomorrow.

Cheers

**Pull request merged**
